version: '2'
services:
  axinfu_echo:
    image: axf-echo
    command: uwsgi --processes=1 -M --gevent=100 --http-socket :80 -w echo:app
    ports:
      - "8080:80/tcp"
    restart: always

networks:
  default:
    external:
      name: network_default